export const SELECT_LANGUAGE = "SELECT_LANGUAGE";
export const FETCH_ITEM = "FETCH_ITEM";
export const SELECT_ITEM = "SELECT_ITEM";
export const SELECT_TIER = "SELECT_TIER";
export const SELECT_ENCHANTMENT = "SELECT_ENCHANTMENT";
export const SELECT_QUALITY = "SELECT_QUALITY";
export const ITEM_ERROR = "ITEM_ERROR";
